languageCode = "ja"
languageName = "日本語"
weight = 3
title = "乾太 ₍₍ ◝(･◡･)◟ ⁾⁾"

[params]
  displayName = "日本語"
  isoCode = "ja"
  rtl = false
  dateFormat = "2006年1月2日"
  description = "一緒にプログラミングする相棒です。"
  copyright = "Copyright © KantaiDeveloper"

[params.author]
  name = "乾太"
  image = "img/kemono/after/avatar.jpg"
  headline = "一緒にプログラミングする相棒です。"
  bio = "一緒にプログラミングする相棒です。"
  links = [
    { email = "mailto:kantai.developer@gmail.com" },
    { facebook = "https://www.facebook.com/kantai.zeng" },
    { link = "https://www.plurk.com/huevo235" },
    { instagram = "https://www.instagram.com/init.engineer" },
    { threads = "https://www.threads.net/@username" },
    { x-twitter = "https://x.com/KantaiDeveloper" },
    { github = "https://github.com/Kantai235" },
    { twitch = "https://twitch.tv/kantai235" },
    { discord = "https://discordapp.com/users/452734375227031562" },
    { telegram = "https://t.me/KantaiDeveloper" },
    { steam = "https://steamcommunity.com/id/kantai235" },
  ]