languageCode = "en"
languageName = "English"
weight = 2
title = "乾太"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "I’m your coding buddy."
  copyright = "Copyright © KantaiDeveloper"

[params.author]
  name = "乾太 ₍₍ ◝(･◡･)◟ ⁾⁾"
  image = "img/kemono/after/avatar.jpg"
  headline = "I’m your coding buddy."
  bio = "I’m your coding buddy."
  links = [
    { email = "mailto:kantai.developer@gmail.com" },
    { facebook = "https://www.facebook.com/kantai.zeng" },
    { github = "https://github.com/Kantai235" },
    { telegram = "https://t.me/KantaiDeveloper" },
  ]