languageCode = "zh-tw"
languageName = "繁體中文"
weight = 1
title = "乾太"

[params]
  displayName = "繁體中文"
  isoCode = "zh-TW"
  rtl = false
  dateFormat = "2006年1月2日"
  description = "一起寫程式的好朋友。"
  copyright = "Copyright © KantaiDeveloper"

[params.author]
  name = "乾太 ₍₍ ◝(･◡･)◟ ⁾⁾"
  image = "img/kemono/after/avatar.jpg"
  headline = "一起寫程式的好朋友。"
  bio = "一起寫程式的好朋友。"
  links = [
    { email = "mailto:kantai.developer@gmail.com" },
    { facebook = "https://www.facebook.com/kantai.zeng" },
    { github = "https://github.com/Kantai235" },
    { telegram = "https://t.me/KantaiDeveloper" },
  ]