# Site Settings
title: 乾太 | 我在人間當工程師
email: kantai.developer@gmail.com
description: 我在人間當工程師
og_type: website
fb_app_id: 3239038076112764
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kantai235.github.io" # the base hostname & protocol for your site
google_analytics: "UA-89952948-1"

# User Settings
username: Kantai
user_description: 我在人間當工程師
disqus_username: kantai235

# Social Media
# Remove the item if you don't need it
github_username: Kantai235
facebook_username: kantai.zeng
# twitter_username: twitter_username
# instagram_username: instagram_username
# linkedin_username: linkedin_username
medium_username: kantai_developer

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: 首頁 Home
    url: /
  - title: 技術文章 Tutorial
    url: /tutorial/
  - title: 開箱文 Unboxing
    url: /unboxing/
  - title: 線上工具 Tools
    url: /tools/
  - title: 產生器 Generator
    url: /generator/
  - title: 快速查表 Article
    url: /article/
  - title: 關於我 About
    url: /about/
  - title: 聯絡我 Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
