# Dependencies
markdown            : redcarpet
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
gems                : ["jekyll-paginate", "jekyll-gist"]

# Permalinks
permalink           : pretty

# Setup
title               : 乾太 Kantai
tagline             : '這裡記錄著我的大小事。'
description         : '傳說中的邊緣工程師。'
baseurl             : /

author              : 乾太
name                : '乾太'
url                 : https://Kantai235.github.io/

paginate            : 5

# Custom vars
version             : 0.1.0
facebook_username   : Zneg.Ya.Fen
twitter_username    : banana_huevo
github_username     : Kantai235