baseURL = 'https://blog.init.engineer'
title = '我不會寫程式'
theme = 'blowfish'

# 多語言配置
defaultContentLanguage = 'zh-tw'

[languages]
  [languages.zh-tw]
    title = '我不會寫程式'
    languageName = '繁體中文'
    weight = 1

[params]
  description = '軟體工程師與獸控的雙重身份'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"