name: Deploy Hugo site to GitHub Pages

on:
  # 在推送到主分支時觸發工作流程
  push:
    branches: [ "master" ]

  # 允許手動觸發工作流程
  workflow_dispatch:

# 設定 GITHUB_TOKEN 的權限以允許部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允許一個部署同時進行
concurrency:
  group: "pages"
  cancel-in-progress: false

# 預設為 bash
defaults:
  run:
    shell: bash

jobs:
  # 構建網站
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.148.2
    steps:
      - name: 安裝 Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          
      - name: 安裝 Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 設定 Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: 安裝 Node.js 依賴
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: 使用 Hugo 建置
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: Asia/Taipei
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"          
      - name: 上傳 artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # 部署網站
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4